spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todomanager
    username: root1
    password: root1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update